(ns project-euler.p0002)

;; https://projecteuler.net/problem=2

;; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;; By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


;; Simple solution
(def fib-1
  (->> [0 1]
       (iterate (fn [[a b]] [b (+ a b)]))
       (map first)))

(take 10 fib-1)

(reduce + (map (fn [x]
                 (if (and (> 4000000 x) (even? x))
                   x 0))
               (take 1000000 fib-1)))
;; => 4613732

;; Optimize method
(def fib-2
  (lazy-cat [0 1] (map + fib-2 (rest fib-2))))

(take 10 fib-2)

(reduce +
        (filter even?
                (take-while #(< % 4000000) fib-2)))
;; => 4613732